export const kialiActions = {
    SET_INFO: "SET_INFO",
    SET_CONFIG: "SET_CONFIG",
    SET_ALERTS: "SET_ALERT",
    SET_NAMESPACES: "SET_NAMESPACES",
    SET_ACTIVE_NAMESPACES: "SET_ACTIVE_NAMESPACES"
  };